### ISSUE TITLE
Using openshift_storage_glusterfs_storageclass default value

### ISSUE THREAD

**Issue by simon3z** [karmab/kubevirt_sprint_demo#6]
Isn't this the default already?

https://github.com/karmab/kubevirt_sprint_demo/blob/4aefd8a147a00f2b392171fdbb1b94e747bae630/installation/hosts#L22

**Comment by karmab** [comment]
this flag makes sure the storage class is created, while another parameter sets it as default one (openshift_storage_glusterfs_storageclass_default)

**Comment by simon3z** [comment]
> this flag makes sure the storage class is created, while another parameter sets it as default one (openshift_storage_glusterfs_storageclass_default)

@karmab, understood, but question was if it is the default value already (so we can drop it). It seems it should be:

https://github.com/openshift/openshift-ansible/blame/f9c36ca6ce6d36b7703c8926f14e16af797a98f9/roles/openshift_storage_glusterfs/README.md#L84

**Comment by simon3z** [comment]
@karmab do you think we can reopen this based on my [previous comment](https://github.com/karmab/kubevirt_sprint_demo/issues/6#issuecomment-378514899)?
